version: '2'

services:
  jupyterlab:
    image: jupyterlab:0_0_1
    container_name: jupyterlab
    environment:
      - STANDALONE="YES"
      - JUPYTERPORT=8900
    ports:
      - "8900:8900"
    volumes: 
      - jupyter-vol:/data/jupyter/

volumes:
  jupyter-vol: