version: '2'
services:
  sparkmaster:
    image: sparkmaster:0_0_1
    hostname: sparkmaster  
    environment:
      - MASTER_PORT=7077
      - MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080" #Web Interface Master
      - "7077:7077" #Master Port
# Setup the jupyter lab
  jupyterlab:
    image: jupyterlab:0_0_1
    hostname: jupyterlab
    depends_on:
      - sparkmaster
    links:
      - sparkmaster
    environment:
      - STANDALONE=NO
      - JUPYTERPORT=8900
      - MASTER_HOSTNAME=sparkmaster
      - MASTER_PORT=7077
    ports:
      - "8900:8900" # WEB interface JupyterLab
    volumes: 
      - jupyter-vol:/data/jupyter/
# Setup the Worker Node 1.
  sparkworker:
    image: sparkworker:0_0_1
    hostname: sparkworker
    depends_on:
      - sparkmaster
    links:
      - sparkmaster
    environment:
      - MASTER_HOSTNAME=sparkmaster
      - WORKER_WEBUI_PORT=8081
      - MASTER_PORT=7077
    ports:
      - "8081-8090:8081" # WEB interface worker
volumes:
  jupyter-vol: