version: '2'
services:
  sparkmaster:
    image: sparkmaster:0_0_1
    container_name: sparkmaster
    hostname: sparkmaster    
    ports:
      - "8080:8080" #Web Interface Master
      - "7077:7077" #Master Port
# Setup the jupyter.
  jupyter:
    image: jupyterlab:0_0_1:0_0_1
    hostname: jupyter
    depends_on:
      - sparkmaster
    links:
      - sparkmaster
    environment:
      - MASTER_HOSTNAME=sparkmaster
      - DISTRIBUTED=1
    ports:
      - "8081:8081" 
# Setup the Worker Node 1.
  sparkworker:
    image: sparkworker:0_0_1
    hostname: sparkworker
    depends_on:
      - sparkmaster
    links:
      - sparkmaster
    environment:
      - MASTER_HOSTNAME=sparkmaster
      - WORKER_WEBUI_PORT=8081
      - MASTER_PORT=7077
    ports:
      - "8081-8090:8081" # WEB interface worker
 
